import {
  completeEmailDigestRun,
  failEmailDigestRun,
  listOpportunities,
  upsertEmailDigestRun,
} from "@/lib/db";
import { sendEmail } from "@/lib/email";

function getWeekStart(): string {
  const d = new Date();
  const day = d.getDay();
  const diff = d.getDate() - day + (day === 0 ? -6 : 1);
  const monday = new Date(d.setDate(diff));
  return monday.toISOString().slice(0, 10);
}

export async function sendWeeklyDigest(domain: string): Promise<void> {
  const toEmail = process.env.DIGEST_TO_EMAIL ?? "";
  if (!toEmail) throw new Error("DIGEST_TO_EMAIL not configured");

  const weekStart = getWeekStart();
  const digestId = upsertEmailDigestRun(domain, weekStart);

  try {
    const opportunities = listOpportunities({ domain, status: "open", limit: 10 });

    const html = buildDigestHtml(domain, weekStart, opportunities);
    const text = buildDigestText(domain, weekStart, opportunities);

    await sendEmail({
      to: toEmail,
      subject: `Weekly SEO Digest — ${domain} — ${weekStart}`,
      html,
      text,
    });

    completeEmailDigestRun(digestId, { domain, weekStart, opportunityCount: opportunities.length });
  } catch (err) {
    failEmailDigestRun(digestId, err instanceof Error ? err.message : "Unknown error");
    throw err;
  }
}

function buildDigestHtml(domain: string, weekStart: string, opps: ReturnType<typeof listOpportunities>): string {
  const rows = opps.map((o) => `
    <tr>
      <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb"><span style="background:${priorityColor(o.priority)};color:#fff;padding:2px 8px;border-radius:4px;font-size:12px">${o.priority}</span></td>
      <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb">${o.title}</td>
      <td style="padding:8px 12px;border-bottom:1px solid #e5e7eb;font-size:13px;color:#6b7280">${o.recommendedAction}</td>
    </tr>`).join("");

  return `
<!DOCTYPE html>
<html>
<head><meta charset="utf-8"></head>
<body style="font-family:system-ui,sans-serif;background:#f9fafb;padding:32px">
  <div style="max-width:700px;margin:0 auto;background:#fff;border-radius:8px;padding:32px;box-shadow:0 1px 3px rgba(0,0,0,0.1)">
    <h1 style="color:#111827;margin:0 0 4px">Weekly SEO Digest</h1>
    <p style="color:#6b7280;margin:0 0 24px">${domain} · Week of ${weekStart}</p>
    ${opps.length === 0
      ? `<p style="color:#6b7280">No open opportunities this week.</p>`
      : `<table style="width:100%;border-collapse:collapse">
          <thead><tr>
            <th style="text-align:left;padding:8px 12px;background:#f3f4f6;font-size:12px;text-transform:uppercase;color:#6b7280">Priority</th>
            <th style="text-align:left;padding:8px 12px;background:#f3f4f6;font-size:12px;text-transform:uppercase;color:#6b7280">Opportunity</th>
            <th style="text-align:left;padding:8px 12px;background:#f3f4f6;font-size:12px;text-transform:uppercase;color:#6b7280">Action</th>
          </tr></thead>
          <tbody>${rows}</tbody>
        </table>`
    }
    <p style="margin-top:24px;font-size:13px;color:#9ca3af">Generated by your local AI SEO tool.</p>
  </div>
</body>
</html>`;
}

function buildDigestText(domain: string, weekStart: string, opps: ReturnType<typeof listOpportunities>): string {
  const lines = [`Weekly SEO Digest — ${domain} — ${weekStart}`, ""];
  for (const o of opps) {
    lines.push(`[${o.priority.toUpperCase()}] ${o.title}`);
    lines.push(`  → ${o.recommendedAction}`);
    lines.push("");
  }
  return lines.join("\n");
}

function priorityColor(p: string): string {
  const map: Record<string, string> = { critical: "#dc2626", high: "#ea580c", medium: "#d97706", low: "#6b7280" };
  return map[p] ?? "#6b7280";
}
